config/routes.rb
Rails.application.routes.draw do
  get 'live', to:"facebook_videos#live"
  get '/videos/:id/video', to: 'galleries#serve_video'
  get '/images/:id/video', to: 'galleries#serve_video'
  resources :facebook_videos, param: :slug, :path => "videos"
  resources :helps, :path => "help", param: :slug do
  end
  get "help/:category/create", to:"helps#new", as:"help_create_subpage"

  resources :payments do
    post "payment", to:"payments#braintree_processing", as:"braintree_processing"
    get "paid", to:"payments#paid", as:"paid"
  end
  resources :invoices do
    get "checkout", to:"invoices#checkout", as:"checkout"
    post "payment", to:"invoices#payment", as:"payment"
    get "refund", to:"invoices#refund", as:"refund"
  end
  get '/galleries/:id/view', to: 'galleries#show_file',as:"gallery_show_file"
  get '/galleries/:id/select', to: 'galleries#file_select',as:"gallery_file_select"
  get '/galleries/:id/:filename', to: 'galleries#serve_file', as:"file_friendly"
  patch '/galleries/:id/upload', to: 'galleries#upload'
  get '/galleries/:id/upload', to: 'galleries#upload'
  resources :galleries
  resources :emails
  resources :bibles
  get "bibles/:id/load/", to:"bibles#load", as:"load_bible"
  get "bibles/:id/load/:book_index", to:"bibles#load_book", as:"load_bible_book"
  get "emails/:id/send/", to:"emails#send_email"
  patch "emails/:id/send/", to:"emails#submit_email_send"
  resources :articles, param: :slug
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
    passwords: 'users/passwords',

  }
  devise_scope :user do
    get "/users/import", to:"users/registrations#import"
    post "/users/import", to:"users/registrations#do_import", as:'user_import'
    get "/users/:id", to:"users/registrations#show", as:'user'
    get "/users/", to:"users/registrations#index"
    get "/users/:id/edit", to:"users/registrations#edit"
    patch "/users/:id", to:"users/registrations#update"
    get "my-profile", to:"users/registrations#edit"
    get "my-courses", to:"users/registrations#my_courses"
    get "my-pets", to:"users/registrations#my_pets"
    delete "/users/:id", to:"users/registrations#destroy"
  end
  get "sign_in", to:redirect('/users/sign_in')
  #get "sign_out", to:redirect('/users/sign_out')
  post "component/:component_id/", to:"pages#component_preview", as:"component"
  post "pages/:slug/component/:component_id/", to:"pages#component_preview", as:"page_component"
  get "component/:component_id/settings", to:"pages#component_settings"
  get "privacy", to:"static_pages#privacy"
  resources 'pages', param: :slug, controller: 'pages'
  # resources 'lessons', param: :slug, controller: 'lessons'

  root to:"pages#home"

resources :courses, param: :slug do
    get "enroll", to:"courses#enroll_student", as:"enrollment"
    post "enroll", to:"courses#enroll"
    get '/lessons/import', to:"lessons#import"
    post '/lessons/import', to:"lessons#do_import"
    delete '/lessons/:slug/delete_file/:id', to: 'lessons#delete_file'
    resources :lessons, param: :slug do
      post '/slides/reorder', to:'lessons#reorder_slides',as:"slides_reorder"
      get '/videos/:filename', to: 'lessons#show_video'
      get '/files/:filename', to: 'lessons#show_file',as:"file"
      get '/slides/new', to:'lessons#new_slide'
      post '/slides/new', to:'lessons#create_slide'
      get '/slides/:index', to:'lessons#show_slide', as:"slide"
      get '/slides/:index/edit', to:'lessons#edit_slide'
      post '/slides/:index/edit', to:'lessons#update_slide'
      delete '/slides/:index', to:'lessons#delete_slide'
      post "/quizzes/:id", to:"quizzes#update"
      post '/upload', to: 'lessons#upload'
      patch '/upload', to: 'lessons#upload'
      post '/chat', to: 'lessons#send_message', as:"chat"
      resource :quiz do
        post '/response', to:'quizzes#student_response'
        post '/slide_response', to:'quizzes#student_response_partial', as:"partial_response"
        get '/:user_id/review', to:'quizzes#instructor_review'
        post '/:user_id/review', to:'quizzes#submit_instructor_review'
      end
    end
    resources :chapters, param: :slug do
      get '/lessons/import', to:"lessons#import_into_chapter"
      post '/lessons/import', to:"lessons#do_import_into_chapter"
      delete '/lessons/:slug/delete_file/:id', to: 'lessons#delete_file'
      get '/lessons/:slug/videos/:filename', to: 'lessons#show_video'
      resources :lessons, param: :slug do
        get '/files/:filename', to: 'lessons#show_file',as:"file"
        get '/videos/:filename', to: 'lessons#show_video'
        patch '/upload', to: 'lessons#upload', as:"upload"
        post '/upload', to: 'lessons#upload'
        get '/slides/new', to:'lessons#new_slide'
        post '/slides/new', to:'lessons#create_slide'
        post '/slides/reorder', to:'lessons#reorder_slides',as:"slides_reorder"
        get '/slides/:index', to:'lessons#show_slide', as:"slide"
        get '/slides/:index/edit', to:'lessons#edit_slide'
        post '/slides/:index/edit', to:'lessons#update_slide'
        delete '/slides/:index', to:'lessons#delete_slide'
        post "/quizzes/:id", to:"quizzes#update"
        resources :quizzes do
          post '/:id/response', to:'quizzes#student_response'
          post '/:id/slide_response', to:'quizzes#student_response_partial'
          get '/:user_id/review', to:'quizzes#instructor_review'
          post '/:user_id/review', to:'quizzes#submit_instructor_review'
        end
      end
    end
  end
end

module CustomUrlHelper
  def lesson_path(lesson)
    if(lesson.chapter.present?)
      course_chapter_lesson_path(lesson.course, lesson.chapter,lesson)
    else
      course_lesson_path(lesson.course,lesson)
    end
  end
  def lesson_url(lesson)
    if(lesson.chapter.present?)
      course_chapter_lesson_url(lesson.course, lesson.chapter,lesson)
    else
      course_lesson_url(lesson.course,lesson)
    end
  end
  def lesson_slide_url(lesson,index)
    if(lesson.chapter.present?)
      course_chapter_lesson_slide_url(lesson.course, lesson.chapter,lesson,index)
    else
      course_lesson_slide_url(lesson.course,lesson,index)
    end
  end
  def lesson_slide_path(lesson,index)
    if(lesson.chapter.present?)
      course_chapter_lesson_slide_url(lesson.course, lesson.chapter,lesson,index)
    else
      course_lesson_slide_url(lesson.course,lesson,index)
    end
  end
  def lesson_slides_reorder_path(lesson)
    if(lesson.chapter.present?)
      course_chapter_lesson_slides_reorder_path(lesson.course,lesson.chapter,lesson)
    else
      course_lesson_slides_reorder_path(lesson.course,lesson)
    end
  end
  def edit_lesson_path(lesson)
    if(lesson.chapter.present?)
      edit_course_chapter_lesson_path(lesson.course, lesson.chapter,lesson)
    else
      edit_course_lesson_path(lesson.course,lesson)
    end
  end
  def new_lesson_path(entity)
    if(entity.class.name == "Chapter")
      new_course_chapter_lesson_path(entity.course, entity)
    elsif(entity.class.name == "Course")
      new_course_lesson_path(entity)
    end
  end
  def new_lesson_url(entity)
    if(entity.class.name == "Chapter")
      new_course_chapter_lesson_url(entity.course, entity)
    elsif(entity.class.name == "Course")
      new_course_lesson_url(entity)
    end
  end
  def edit_lesson_url(lesson)
    if(lesson.chapter.present?)
      edit_course_chapter_lesson_url(lesson.course, lesson.chapter,lesson)
    else
      edit_course_lesson_url(lesson.course,lesson)
    end
  end
  def lesson_upload_path(lesson)
    if(lesson.chapter.present?)
      course_chapter_lesson_path(lesson.course,lesson.chapter,lesson)+"/upload"
    else
      course_lesson_path(lesson.course,lesson)+"/upload"
    end
  end
  def lesson_upload_url(lesson)
    if(lesson.chapter.present?)
      course_chapter_lesson_url(lesson.course,lesson.chapter,lesson)+"/upload"
    else
      course_lesson_url(lesson.course,lesson)+"/upload"
    end
  end
  def lesson_file_path(lesson,filename)
    if(lesson.chapter.present?)
      course_chapter_lesson_file_path(lesson.course,lesson.chapter,lesson,filename)
    else
      course_lesson_file_path(lesson.course,lesson,filename)
    end
  end
  def lesson_file_url(lesson,filename)
    if(lesson.chapter.present?)
      course_chapter_lesson_file_url(lesson.course,lesson.chapter,lesson,filename)
    else
      course_lesson_file_url(lesson.course,lesson,filename)
    end
  end
  def lesson_quiz_path(lesson)
    if(lesson.chapter.present?)
      course_chapter_lesson_quiz_path(lesson.course,lesson.chapter,lesson,lesson.quiz)
    else
      course_lesson_quiz_path(lesson.course,lesson,lesson.quiz)
    end
  end
  def edit_lesson_quiz_path(lesson)
    if(lesson.chapter.present?)
      edit_course_chapter_lesson_quiz_path(lesson.course,lesson.chapter,lesson,lesson.quiz)
    else
      edit_course_lesson_quiz_path(lesson.course,lesson,lesson.quiz)
    end
  end
end

# Works at Rails 4.2.6, for older versions try http://stackoverflow.com/a/31957323/474597
Rails.application.routes.named_routes.url_helpers_module.send(:include, CustomUrlHelper)

app/models/static_page.rb
class StaticPage < ApplicationRecord
  serialize :components, Array
  self.table_name = "pages"
  after_initialize do |page|
    if(page.slug != page.name.parameterize)
      page.slug = page.name.parameterize
    end
  end

  def self.component_options
    excludes = ["customizable_component","modal_component","messenger_component"]
    results = Dir["app/components/*.rb"].collect{|path| path.split("/").last.split(".").first}.collect{|c| [c.titleize, c]}.select{|c| c[1].camelcase.constantize.respond_to? :params}
    results = results.select{|item| !excludes.include?(item[1])}
    return results
  end

  def self.page_options
    results = StaticPage.all.collect{|p| [p.name.titleize, p.pointer] }
    return results
  end

  def self.data_sources
    Dir["app/models/*.rb"].collect{|path| [path.split("/").last.split(".").first, path.split("/").last.split(".").first.titleize]}
  end

  def add_component(name, component)
    self.components << component
  end

  def to_param
    slug
  end
  def update(params)

    params[:components].each_index do |i|
      c = params[:components][i]
      params[:components][i] = ComponentSettings.new(c[:name])
      if(c[:args].present?)
        params[:components][i].args = c[:args].symbolize_keys
      end
    end
    super(params)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
before_action :set_page, only: [:show, :edit, :update, :destroy]
  layout 'application'

  def index
    return unless requester_is_staff
    # @pages = StaticPage.all
  end

  def home
    @page = StaticPage.find_by slug:"home"
    @components = @page.components
  end

  def about_us
    # @page = StaticPage.find_by slug:"home"
    # @components = []
    # @page.components.each do |component|
    #   @components << component[:name].camelcase.constantize.new(**component[:args].symbolize_keys)
    # end
    render "about-us"
  end
  def privacy
    # @page = StaticPage.find_by slug:"home"
    # @components = []
    # @page.components.each do |component|
    #   @components << component[:name].camelcase.constantize.new(**component[:args].symbolize_keys)
    # end
    render "privacy"
  end

  def show
    @components = @page.components
    # render params[:slug]
  end

  def new
    return unless requester_is_staff
  end

  def create
    return unless requester_is_staff
    if @page.save
      redirect_to @page, notice: 'Page was successfully created.'
    else
      render :new
    end
  end

  def edit
    return unless requester_is_staff
  end

  def component_preview
    return unless requester_is_staff
    component_params
    render(partial:"component_preview",layout:false, locals:{component:ComponentSettings.new(@name,@args)})
  end

  def component_settings
    return unless requester_is_staff
    set_component
    render(partial:"component_settings_embedded",layout:false, locals:{component:@component})
  end

  def update
    return unless requester_is_staff
    if @page.update(page_params)
      redirect_to @page, notice: 'Page was successfully updated.'
    else
      render :edit
    end
  end



  def destroy
    return unless requester_is_staff
    @page.destroy
    redirect_to pages_url, notice: 'Page was successfully destroyed.'
  end
  private


  def page_params
    p = params.require(:page).permit(:name,components:[:name,args:{}]).to_h.symbolize_keys
    p[:components] = p[:components].map{|c| c.to_h.symbolize_keys; }
    return p
  end

  def component_params
    if(params[:args])
      @args = params[:args].permit!.to_h.symbolize_keys
    end
    @name = params[:name].to_s
  end


  def set_component
    set_page
    id_is_name = (params[:component_id].present? && params[:component_id].to_i == 0 && params[:component_id] != "0")
    # byebug
    if(id_is_name)
      @component = ComponentSettings.new(params[:component_id])
    elsif(params[:component_id].present?)
      @component = @page.components[params[:component_id].to_i]
    end
  end

  def set_page
    @page = StaticPage.find_by slug: params[:slug]
  end


end

app/views/static_pages/_component_preview.html.erb
<%= render(component.view(@args)) %>

app/views/static_pages/_component_select.html.erb
<div class="component-select" data-controller="component-editor" data-component-editor-index="<%= index %>">
  <% if(component.present?) %>
    <%= form.select("components[][name]".to_sym, StaticPage.component_options, {selected:component.name, label:"Component Type",include_blank:"Select a component type..."}, class:"componentType", data:{action:"component-editor#changeType"}) %>
    Preview:
    <div class="component-preview" style="zoom:.8" data-target="component-editor.preview">
      <%= render("component_preview", component:component) %>
    </div>
    <div class="settings border-bottom" data-target="component-editor.settings">
      <%= render("component_settings",form:form, component:component) %>
    </div>
  <% elsif(index == 0) %>
    <%= form.select("components[][name]".to_sym, StaticPage.component_options, {label:"Component Type", include_blank:"Select a component type..."}, class:"componentType", data:{action:"component-editor#changeType"}) %>
    <div class="component-preview" data-target="component-editor.preview">
    </div>
    <div class="settings" data-target="component-editor.settings">
    </div>
  <% end %>
</div>

app/views/static_pages/_component_settings.html.erb
<% component.keys.each do |key| %>
  <%= component.field_for(key,form) %>
<% end %>

app/views/static_pages/_component_settings_embedded.html.erb
<%= bootstrap_form_with(model:@page, local: true) do |form| %>
  <%= render("component_settings",form:form, component:component) %>
<% end %>

app/views/static_pages/_form.html.erb
<%= bootstrap_form_with(model:page, local: true) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div id="components">
    <%= form.submit "Save Changes", class:"btn btn-default" %>
    <div class="field">
      <%= form.text_field :name %>
    </div>
    <% if(page.components.length > 0)
      page.components.each_with_index do |component,i| %>
      <div class="component" id="component-<%= i %>">
        <div class="field">
          <%= render "component_select", index:i, form:form, component:component %>
        </div>
        <% end %>
      </div>
    <% else %>
    <div class="component" id="component-0">
      <div class="field">
        <%= render "component_select", index:0, form:form, component:nil %>
      </div>
    </div>
    <% end %>
  </div>

  <div class="addComponent">
    <%= link_to "+ Add Component", "#", class:"btn btn-secondary", id:"addComponent" %>
  </div>
  <div class="actions">
    <%= form.submit "Save Changes", class:"btn btn-default" %>
  </div>
<% end %>

<script type="text/javascript">
  if(!!$)
  {
    $("body").ready(()=>{


      $("#addComponent").click((e)=>{
        e.preventDefault()
        numComponents = $(".component").length
        i = parseInt($(".component")[numComponents-1].id.split("-")[1])
        nextId = "component-"+(i+1)
        component_selector = $(`#component-${i}`)[0].cloneNode()
        component_selector.id = nextId
        $(component_selector).html($(`#component-${i}`).html())
        $(".component-preview",component_selector).html("")
        $(".settings",component_selector).html("")
        $(".settings",component_selector).data("")
        $("#components").append(component_selector)
        $("select","#"+component_selector.id).val("")

      })
    })
  }

</script>

app/views/static_pages/about-us.html.erb
<div class='container'>
  <%= render EventsComponent.new %>
</div>

app/views/static_pages/edit.html.erb
<h1>Editing Page</h1>
<%= toolbar([back_button(@course)]) %>
<%= render 'form', page: @page %>

app/views/static_pages/home.html.erb
<!-- <div class='container'>
  <h1 class="display-4">Online Activity Center</h1>
  <p class="lead">Welcome! Come worship the Lord with us!</p>
  <hr class="my-4">
  <p>We'll use this space to offer Bible Study, VBS and more!</p>
  <p class="lead">
    <a class="btn btn-default btn-lg" href="/pages/about-us/" role="button">Learn More</a>
  </p>
  <div class="w-100">&nbsp;</div>
</div> -->
<% @components.each do |component|%>
  <%= render(component.view) %>
<% end %>
<% Article.all.each do |article|%>
<hr>
  <%= render("articles/article_blurb", article:article)%>
<% end %>

app/views/static_pages/index.html.erb

<%= toolbar([back_button(:back),link_to('New Page', new_page_path, class: 'btn btn-sm btn-default')]) %>

<h1>Pages</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan=3></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td> <%= page.name.titleize %> </td>
        <td><%= link_to 'View', page_path(page), class: 'btn btn-sm btn-default' %></td>
        <td><%= link_to 'Edit', edit_page_path(page), class: 'btn btn-sm btn-secondary' %></td>
        <td><%= link_to 'Delete', page, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %></td>
      </tr>
     <% end %>
  </tbody>
</table>

<br>

app/views/static_pages/new.html.erb

<h1>New Page</h1>
<%= toolbar([back_button(@course)]) %>
<%= render 'form', page: @page %>

app/views/static_pages/privacy.html.erb
<div class='container'>

  <h2>Privacy Policy</h2>
  <p>Your privacy is important to us. It is Memorial United Methodist Church Austin&#39;s policy to respect your privacy and comply with any applicable law and regulation regarding any personal information we may collect about you, including across our website, <a href="http://www.memorialumcaustin.com/">http://www.memorialumcaustin.com/</a>, and other sites we own and operate. </p>
  <p>This policy is effective as of 19 March 2021 and was last updated on 19 March 2021. </p>
  <h3>Information We Collect</h3>
  <p>Information we collect includes both information you knowingly and actively provide us when using or participating in any of our services and promotions, and any information automatically sent by your devices in the course of accessing our products and services. </p>
  <h4>Log Data</h4>
  <p>When you visit our website, our servers may automatically log the standard data provided by your web browser. It may include your device’s Internet Protocol (IP) address, your browser type and version, the pages you visit, the time and date of your visit, the time spent on each page, other details about your visit, and technical details that occur in conjunction with any errors you may encounter. </p>
  <p>Please be aware that while this information may not be personally identifying by itself, it may be possible to combine it with other data to personally identify individual persons. </p>
  <h4>Collection and Use of Information</h4>
  <p>We may collect personal information from you when you do any of the following on our website: </p>
  <ul>
     <li>Use a mobile device or web browser to access our content</li>
     <li>Contact us via email, social media, or on any similar technologies</li>
     <li>When you mention us on social media</li>
  </ul>
  <p>We may collect, hold, use, and disclose information for the following purposes, and personal information will not be further processed in a manner that is incompatible with these purposes: </p>
  <p>Please be aware that we may combine information we collect about you with general information or research data we receive from other trusted sources. </p>
  <h4>Security of Your Personal Information</h4>
  <p>When we collect and process personal information, and while we retain this information, we will protect it within commercially acceptable means to prevent loss and theft, as well as unauthorized access, disclosure, copying, use, or modification. </p>
  <p>Although we will do our best to protect the personal information you provide to us, we advise that no method of electronic transmission or storage is 100% secure, and no one can guarantee absolute data security. We will comply with laws applicable to us in respect of any data breach. </p>
  <p>You are responsible for selecting any password and its overall security strength, ensuring the security of your own information within the bounds of our services. </p>
  <h4>How Long We Keep Your Personal Information</h4>
  <p>We keep your personal information only for as long as we need to. This time period may depend on what we are using your information for, in accordance with this privacy policy. If your personal information is no longer required, we will delete it or make it anonymous by removing all details that identify you. </p>
  <p>However, if necessary, we may retain your personal information for our compliance with a legal, accounting, or reporting obligation or for archiving purposes in the public interest, scientific, or historical research purposes or statistical purposes. </p>
  <h3>Children’s Privacy</h3>
  <p>We do not aim any of our products or services directly at children under the age of 13, and we do not knowingly collect personal information about children under 13. </p>
  <h3>Disclosure of Personal Information to Third Parties</h3>
  <p>We may disclose personal information to: </p>
  <ul>
     <li>a parent, subsidiary, or affiliate of our company</li>
     <li>third party service providers for the purpose of enabling them to provide their services, for example, IT service providers, data storage, hosting and server providers, advertisers, or analytics platforms</li>
     <li>our employees, contractors, and/or related entities</li>
     <li>our existing or potential agents or business partners</li>
     <li>sponsors or promoters of any competition, sweepstakes, or promotion we run</li>
     <li>courts, tribunals, regulatory authorities, and law enforcement officers, as required by law, in connection with any actual or prospective legal proceedings, or in order to establish, exercise, or defend our legal rights</li>
     <li>third parties, including agents or sub-contractors, who assist us in providing information, products, services, or direct marketing to you third parties to collect and process data</li>
  </ul>
  <h3>International Transfers of Personal Information</h3>
  <p>The personal information we collect is stored and/or processed where we or our partners, affiliates, and third-party providers maintain facilities. Please be aware that the locations to which we store, process, or transfer your personal information may not have the same data protection laws as the country in which you initially provided the information. If we transfer your personal information to third parties in other countries: (i) we will perform those transfers in accordance with the requirements of applicable law; and (ii) we will protect the transferred personal information in accordance with this privacy policy. </p>
  <h3>Your Rights and Controlling Your Personal Information</h3>
  <p>You always retain the right to withhold personal information from us, with the understanding that your experience of our website may be affected. We will not discriminate against you for exercising any of your rights over your personal information. If you do provide us with personal information you understand that we will collect, hold, use and disclose it in accordance with this privacy policy. You retain the right to request details of any personal information we hold about you. </p>
  <p>If we receive personal information about you from a third party, we will protect it as set out in this privacy policy. If you are a third party providing personal information about somebody else, you represent and warrant that you have such person’s consent to provide the personal information to us. </p>
  <p>If you have previously agreed to us using your personal information for direct marketing purposes, you may change your mind at any time. We will provide you with the ability to unsubscribe from our email-database or opt out of communications. Please be aware we may need to request specific information from you to help us confirm your identity. </p>
  <p>If you believe that any information we hold about you is inaccurate, out of date, incomplete, irrelevant, or misleading, please contact us using the details provided in this privacy policy. We will take reasonable steps to correct any information found to be inaccurate, incomplete, misleading, or out of date. </p>
  <p>If you believe that we have breached a relevant data protection law and wish to make a complaint, please contact us using the details below and provide us with full details of the alleged breach. We will promptly investigate your complaint and respond to you, in writing, setting out the outcome of our investigation and the steps we will take to deal with your complaint. You also have the right to contact a regulatory body or data protection authority in relation to your complaint. </p>
  <h3>Use of Cookies</h3>
  <p>We use &ldquo;cookies&rdquo; to collect information about you and your activity across our site. A cookie is a small piece of data that our website stores on your computer, and accesses each time you visit, so we can understand how you use our site. This helps us serve you content based on preferences you have specified. </p>
  <h3>Limits of Our Policy</h3>
  <p>Our website may link to external sites that are not operated by us. Please be aware that we have no control over the content and policies of those sites, and cannot accept responsibility or liability for their respective privacy practices. </p>
  <h3>Changes to This Policy</h3>
  <p>At our discretion, we may change our privacy policy to reflect updates to our business processes, current acceptable practices, or legislative or regulatory changes. If we decide to change this privacy policy, we will post the changes here at the same link by which you are accessing this privacy policy. </p>
  <p>If required by law, we will get your permission or give you the opportunity to opt in to or opt out of, as applicable, any new uses of your personal information. </p>
  <h3>Contact Us</h3>
  <p>For any questions or concerns regarding your privacy, you may contact us using the following details: </p>
  <p>Gregory J Mikeska<br />
  gmikeska07@gmail.com </p>


</div>

app/views/static_pages/show.html.erb
<div class='container'>
  <% @components.each do |component|%>
    <%= render(component.view) %>
  <% end %>
</div>