config/routes.rb
Rails.application.routes.draw do
  get 'live', to:"facebook_videos#live"
  get '/videos/:id/video', to: 'galleries#serve_video'
  get '/images/:id/video', to: 'galleries#serve_video'
  resources :facebook_videos, param: :slug, :path => "videos"
  resources :helps, :path => "help", param: :slug do
  end
  get "help/:category/create", to:"helps#new", as:"help_create_subpage"

  resources :payments do
    post "payment", to:"payments#braintree_processing", as:"braintree_processing"
    get "paid", to:"payments#paid", as:"paid"
  end
  resources :invoices do
    get "checkout", to:"invoices#checkout", as:"checkout"
    post "payment", to:"invoices#payment", as:"payment"
    get "refund", to:"invoices#refund", as:"refund"
  end
  get '/galleries/:id/view', to: 'galleries#show_file',as:"gallery_show_file"
  get '/galleries/:id/select', to: 'galleries#file_select',as:"gallery_file_select"
  get '/galleries/:id/:filename', to: 'galleries#serve_file', as:"file_friendly"
  patch '/galleries/:id/upload', to: 'galleries#upload'
  get '/galleries/:id/upload', to: 'galleries#upload'
  resources :galleries
  resources :emails
  resources :bibles
  get "bibles/:id/load/", to:"bibles#load", as:"load_bible"
  get "bibles/:id/load/:book_index", to:"bibles#load_book", as:"load_bible_book"
  get "emails/:id/send/", to:"emails#send_email"
  patch "emails/:id/send/", to:"emails#submit_email_send"
  resources :articles, param: :slug
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
    passwords: 'users/passwords',

  }
  devise_scope :user do
    get "/users/import", to:"users/registrations#import"
    post "/users/import", to:"users/registrations#do_import", as:'user_import'
    get "/users/:id", to:"users/registrations#show", as:'user'
    get "/users/", to:"users/registrations#index"
    get "/users/:id/edit", to:"users/registrations#edit"
    patch "/users/:id", to:"users/registrations#update"
    get "my-profile", to:"users/registrations#edit"
    get "my-courses", to:"users/registrations#my_courses"
    get "my-pets", to:"users/registrations#my_pets"
    delete "/users/:id", to:"users/registrations#destroy"
  end
  get "sign_in", to:redirect('/users/sign_in')
  #get "sign_out", to:redirect('/users/sign_out')
  post "component/:component_id/", to:"pages#component_preview", as:"component"
  post "pages/:slug/component/:component_id/", to:"pages#component_preview", as:"page_component"
  get "component/:component_id/settings", to:"pages#component_settings"
  get "privacy", to:"static_pages#privacy"
  resources 'pages', param: :slug, controller: 'pages'
  # resources 'lessons', param: :slug, controller: 'lessons'

  root to:"pages#home"

resources :courses, param: :slug do
    get "enroll", to:"courses#enroll_student", as:"enrollment"
    post "enroll", to:"courses#enroll"
    get '/lessons/import', to:"lessons#import"
    post '/lessons/import', to:"lessons#do_import"
    delete '/lessons/:slug/delete_file/:id', to: 'lessons#delete_file'
    resources :lessons, param: :slug do
      post '/slides/reorder', to:'lessons#reorder_slides',as:"slides_reorder"
      get '/videos/:filename', to: 'lessons#show_video'
      get '/files/:filename', to: 'lessons#show_file',as:"file"
      get '/slides/new', to:'lessons#new_slide'
      post '/slides/new', to:'lessons#create_slide'
      get '/slides/:index', to:'lessons#show_slide', as:"slide"
      get '/slides/:index/edit', to:'lessons#edit_slide'
      post '/slides/:index/edit', to:'lessons#update_slide'
      delete '/slides/:index', to:'lessons#delete_slide'
      post "/quizzes/:id", to:"quizzes#update"
      post '/upload', to: 'lessons#upload'
      patch '/upload', to: 'lessons#upload'
      post '/chat', to: 'lessons#send_message', as:"chat"
      resource :quiz do
        post '/response', to:'quizzes#student_response'
        post '/slide_response', to:'quizzes#student_response_partial', as:"partial_response"
        get '/:user_id/review', to:'quizzes#instructor_review'
        post '/:user_id/review', to:'quizzes#submit_instructor_review'
      end
    end
    resources :chapters, param: :slug do
      get '/lessons/import', to:"lessons#import_into_chapter"
      post '/lessons/import', to:"lessons#do_import_into_chapter"
      delete '/lessons/:slug/delete_file/:id', to: 'lessons#delete_file'
      get '/lessons/:slug/videos/:filename', to: 'lessons#show_video'
      resources :lessons, param: :slug do
        get '/files/:filename', to: 'lessons#show_file',as:"file"
        get '/videos/:filename', to: 'lessons#show_video'
        patch '/upload', to: 'lessons#upload', as:"upload"
        post '/upload', to: 'lessons#upload'
        get '/slides/new', to:'lessons#new_slide'
        post '/slides/new', to:'lessons#create_slide'
        post '/slides/reorder', to:'lessons#reorder_slides',as:"slides_reorder"
        get '/slides/:index', to:'lessons#show_slide', as:"slide"
        get '/slides/:index/edit', to:'lessons#edit_slide'
        post '/slides/:index/edit', to:'lessons#update_slide'
        delete '/slides/:index', to:'lessons#delete_slide'
        post "/quizzes/:id", to:"quizzes#update"
        resources :quizzes do
          post '/:id/response', to:'quizzes#student_response'
          post '/:id/slide_response', to:'quizzes#student_response_partial'
          get '/:user_id/review', to:'quizzes#instructor_review'
          post '/:user_id/review', to:'quizzes#submit_instructor_review'
        end
      end
    end
  end
end

module CustomUrlHelper
  def lesson_path(lesson)
    if(lesson.chapter.present?)
      course_chapter_lesson_path(lesson.course, lesson.chapter,lesson)
    else
      course_lesson_path(lesson.course,lesson)
    end
  end
  def lesson_url(lesson)
    if(lesson.chapter.present?)
      course_chapter_lesson_url(lesson.course, lesson.chapter,lesson)
    else
      course_lesson_url(lesson.course,lesson)
    end
  end
  def lesson_slide_url(lesson,index)
    if(lesson.chapter.present?)
      course_chapter_lesson_slide_url(lesson.course, lesson.chapter,lesson,index)
    else
      course_lesson_slide_url(lesson.course,lesson,index)
    end
  end
  def lesson_slide_path(lesson,index)
    if(lesson.chapter.present?)
      course_chapter_lesson_slide_url(lesson.course, lesson.chapter,lesson,index)
    else
      course_lesson_slide_url(lesson.course,lesson,index)
    end
  end
  def lesson_slides_reorder_path(lesson)
    if(lesson.chapter.present?)
      course_chapter_lesson_slides_reorder_path(lesson.course,lesson.chapter,lesson)
    else
      course_lesson_slides_reorder_path(lesson.course,lesson)
    end
  end
  def edit_lesson_path(lesson)
    if(lesson.chapter.present?)
      edit_course_chapter_lesson_path(lesson.course, lesson.chapter,lesson)
    else
      edit_course_lesson_path(lesson.course,lesson)
    end
  end
  def new_lesson_path(entity)
    if(entity.class.name == "Chapter")
      new_course_chapter_lesson_path(entity.course, entity)
    elsif(entity.class.name == "Course")
      new_course_lesson_path(entity)
    end
  end
  def new_lesson_url(entity)
    if(entity.class.name == "Chapter")
      new_course_chapter_lesson_url(entity.course, entity)
    elsif(entity.class.name == "Course")
      new_course_lesson_url(entity)
    end
  end
  def edit_lesson_url(lesson)
    if(lesson.chapter.present?)
      edit_course_chapter_lesson_url(lesson.course, lesson.chapter,lesson)
    else
      edit_course_lesson_url(lesson.course,lesson)
    end
  end
  def lesson_upload_path(lesson)
    if(lesson.chapter.present?)
      course_chapter_lesson_path(lesson.course,lesson.chapter,lesson)+"/upload"
    else
      course_lesson_path(lesson.course,lesson)+"/upload"
    end
  end
  def lesson_upload_url(lesson)
    if(lesson.chapter.present?)
      course_chapter_lesson_url(lesson.course,lesson.chapter,lesson)+"/upload"
    else
      course_lesson_url(lesson.course,lesson)+"/upload"
    end
  end
  def lesson_file_path(lesson,filename)
    if(lesson.chapter.present?)
      course_chapter_lesson_file_path(lesson.course,lesson.chapter,lesson,filename)
    else
      course_lesson_file_path(lesson.course,lesson,filename)
    end
  end
  def lesson_file_url(lesson,filename)
    if(lesson.chapter.present?)
      course_chapter_lesson_file_url(lesson.course,lesson.chapter,lesson,filename)
    else
      course_lesson_file_url(lesson.course,lesson,filename)
    end
  end
  def lesson_quiz_path(lesson)
    if(lesson.chapter.present?)
      course_chapter_lesson_quiz_path(lesson.course,lesson.chapter,lesson,lesson.quiz)
    else
      course_lesson_quiz_path(lesson.course,lesson,lesson.quiz)
    end
  end
  def edit_lesson_quiz_path(lesson)
    if(lesson.chapter.present?)
      edit_course_chapter_lesson_quiz_path(lesson.course,lesson.chapter,lesson,lesson.quiz)
    else
      edit_course_lesson_quiz_path(lesson.course,lesson,lesson.quiz)
    end
  end
end

# Works at Rails 4.2.6, for older versions try http://stackoverflow.com/a/31957323/474597
Rails.application.routes.named_routes.url_helpers_module.send(:include, CustomUrlHelper)

app/models/invoice.rb
require "braintree"
class Invoice < ApplicationRecord
  belongs_to :user
  has_many :enrollments
  has_many :payments
  has_many :courses, through: :enrollments
  after_initialize do |invoice|
    if(invoice.number.nil?)
      suffix = (Time.now.utc.strftime("%S").to_i)*(invoice.user.id)
      invoice.number = Time.now.utc.strftime("%Y%m%d%H%M")+suffix.to_s
    end
  end
  def price_total
    prices = enrollments.collect { |enrollment| enrollment.price }
    return prices.reduce(:+)
  end

  def amount_paid
    payment_list = payments.select{|p| p.status == :settled}.collect { |transaction| Money.new(transaction.amount.to_f*100) }
    if(payment_list.length > 0)
      return payment_list.reduce(:+)
    else
      return 0
    end
  end

  def apply_payment(transaction)
    self.payments << transaction
  end

  def update_payment_status
    payments.each_index do |i|;payment = payments[i]
      updated = Payment.gateway.transaction.find(payment.id)
      payments[i] = updated
    end
    save
  end

  def amount_owed
    price_total - amount_paid
  end

  def status
    if(payments.present? && payments.length > 0)
      if(self.refunded)
        return "refunded"
      end
      statuses = self.payments.collect{|p| p.status}
      if(statuses.length == 1)
        return statuses.first
      else
        if(self.amount_owed > 0)
          response = "partial_#{statuses.last}"
        end
      end

    else
      response = Invoice.status_options.first
    end
    return response
  end
  def status_info(status)
    case status
    when "submitted_for_settlement"
      "The transaction has been submitted for settlement and will be included in the next settlement batch. Settlement happens nightly – the exact time depends on the processor."
    when "settling"
      "The transaction is in the process of being settled. This is a transitory state. A transaction can't be voided once it reaches Settling status, but can be refunded."
    when "settled"
      "The transaction has been settled."
    when "voided"
      "The transaction was voided prior to settlement."
    when "unpaid"
      "The user has added the course but has not yet paid."
    end
  end
  def paid?
    (self.amount_owed == 0 || [:settling,:settled, :submitted_for_settlement].include?(self.payments.first.status))
  end

  def error?
    ["SettlementDeclined","Failed", "GatewayRejected","ProcessorDeclined"].include?(self.status)
  end

  def self.status_options
     ["unpaid","pending","settled"]
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy, :checkout,:payment, :paid, :refund]
  # self.TRANSACTION_SUCCESS_STATUSES = [
  #   Braintree::Transaction::Status::Authorizing,
  #   Braintree::Transaction::Status::Authorized,
  #   Braintree::Transaction::Status::Settled,
  #   Braintree::Transaction::Status::SettlementConfirmed,
  #   Braintree::Transaction::Status::SettlementPending,
  #   Braintree::Transaction::Status::Settling,
  #   Braintree::Transaction::Status::SubmittedForSettlement,
  # ]

  # GET /invoices
  # GET /invoices.json
  def index
    return unless requester_is_staff
    @invoices = Invoice.all
    @invoices.each do |invoice|
      if(invoice.status == "submitted_for_settlement" || invoice.status == "settling")
        invoice.update_payment_status
      end
    end
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
    authorized = (current_user && (current_user == @invoice.user || current_user.isStaff?))
    return unless requester_is_authorized(authorized)
  end

  def checkout
    authorized = (current_user && (current_user == @invoice.user || current_user.isStaff?))
    return unless requester_is_authorized(authorized)
    @payment = Payment.new(invoice:@invoice, user:current_user, amount:@invoice.amount_owed)
    @payment.save
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def refund
    return unless requester_is_staff
    @invoice.payments.each do |transaction|
      if(transaction.status == "settled")
        result = Payment.gateway.transaction.refund(transaction.id)
      else
        result = Payment.gateway.transaction.void(transaction.id)
      end
      byebug
    end
    @invoice.refunded = true
    redirect_to "/invoices/"
  end

  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      if(params[:invoice_id])
        @invoice = Invoice.find(params[:invoice_id])
      else
        @invoice = Invoice.find(params[:id])
      end
    end

    # Only allow a list of trusted parameters through.
    def invoice_params
      params.fetch(:invoice, {})
    end
end

app/views/invoices/_form.html.erb
<%= form_with(model: invoice, local: true) do |form| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
        <% invoice.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invoices/_show.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Course</th>
      <th>Student</th>
      <th>Price</th>
    </tr>
  </thead>

  <tbody>
    <% invoice.enrollments.each do |enrollment| %>
      <tr>
        <td><%= enrollment.course.name %></td>
        <td><%= enrollment.user.name %></td>
        <td>$<%= enrollment.price %></td>
      </tr>
    <% end %>
    <tr>
      <td colspan="2"><strong>Total:</strong></td>
      <td>$<%= invoice.price_total %></td>
    </tr>
    <tr>
      <td colspan="2">Payments Received:</td>
      <td>$<%= invoice.amount_paid %></td>
    </tr>
    <tr>
      <td colspan="2"><strong>Amount Owed:</strong></td>
      <td>$<%= invoice.amount_owed %></td>
    </tr>
  </tbody>
</table>

app/views/invoices/checkout.html.erb
<h1>Checkout - Invoice #<%= @invoice.number %></h1>
<%= render "show",invoice:@invoice %>
<%= render "payments/form",amount:@invoice.amount_owed, payment:@payment %>

app/views/invoices/donate.html.erb
<%= bootstrap_form_with(model: @invoice, local: true) do |form| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
        <% invoice.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    $<%= form.number_field :amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>
<%= toolbar([back_button(:back),view_button(@invoice,content:"View Invoice")]) %>

<%= render 'form', invoice: @invoice %>

app/views/invoices/index.html.erb
<%= toolbar([back_button(:back),link_to('New Invoice', new_invoice_path, class:"btn btn-sm btn-default")]) %>
<h1>Invoices</h1>

<table class="table">
  <thead>
    <tr>
      <th>Invoice #</th>
      <th>User</th>
      <th>Courses</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.number %></td>
        <td><%= invoice.user.name %></td>
        <td><%= invoice.courses.count %></td>
        <% if(!invoice.status_info(invoice.status).nil?) %>
          <td><span title="<%= invoice.status_info(invoice.status) %>" style="font-size: large; color: maroon;">🛈&nbsp</span><%= invoice.status.titleize %></td>
        <% else %>
          <td><%= invoice.status.to_s.titleize %></td>
        <% end %>
        <td><%= view_button(invoice) %></td>
        <td><%= edit_button(edit_invoice_path(invoice), class: 'btn btn-sm btn-secondary') %></td>
        <% if(invoice.status == "unpaid" || invoice.status == "voided" || invoice.status == "refunded" ) %>
          <td><%= delete_button(invoice, title:"Click here to delete the site's record of this transaction. You can still view payment info in Braintree's logs if invoice was paid.") %></td>
          <% else %>
          <td><%= link_to 'Refund', invoice_refund_url(invoice),title:"Click here to refund, or prevent settlement if the payment has not yet settled.", data: { confirm: 'Are you sure?' },class: 'btn btn-sm btn-danger' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<h1>Invoice #<%= @invoice.number %></h1>
<% if(current_user != @invoice.user) %>
<div class="border">
  <div class="row">
    <div class="col">
      <strong>Client Name:</strong>&nbsp<%= @invoice.user.name %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <strong>Status:</strong>&nbsp<%= @invoice.status.titleize %><span title="<%= @invoice.status_info(@invoice.status) %>" style="font-size: large; color: maroon;">&nbsp🛈</span>
    </div>
  </div>
</div>
<% if(@invoice.status == "unpaid" || @invoice.status == "voided" || @invoice.status == "refunded" ) %>
  <%= delete_button(@invoice) %>
<% else %>
  <%= link_to 'Refund', invoice_refund_url(@invoice), title:"Click here to refund, or prevent settlement if the payment has not yet settled.", data: { confirm: 'Are you sure?' },class: 'btn btn-sm btn-danger' %>
<% end %>
<% else %>
  <%= link_to 'Checkout', invoice_checkout_path(@invoice), class: 'btn btn-sm btn-default' %>
<% end %>
<%= link_to 'Back', :back, class: 'btn btn-sm btn-secondary' %>
<%= render "show" %>
<% if(current_user == @invoice.user) %>
  <%= link_to 'Checkout', invoice_checkout_path(@invoice), class: 'btn btn-sm btn-default' %>
<% end %>