config/routes.rb
Rails.application.routes.draw do
  get 'live', to:"facebook_videos#live"
  get '/videos/:id/video', to: 'galleries#serve_video'
  get '/images/:id/video', to: 'galleries#serve_video'
  resources :facebook_videos, param: :slug, :path => "videos"
  resources :helps, :path => "help", param: :slug do
  end
  get "help/:category/create", to:"helps#new", as:"help_create_subpage"

  resources :payments do
    post "payment", to:"payments#braintree_processing", as:"braintree_processing"
    get "paid", to:"payments#paid", as:"paid"
  end
  resources :invoices do
    get "checkout", to:"invoices#checkout", as:"checkout"
    post "payment", to:"invoices#payment", as:"payment"
    get "refund", to:"invoices#refund", as:"refund"
  end
  get '/galleries/:id/view', to: 'galleries#show_file',as:"gallery_show_file"
  get '/galleries/:id/select', to: 'galleries#file_select',as:"gallery_file_select"
  get '/galleries/:id/:filename', to: 'galleries#serve_file', as:"file_friendly"
  patch '/galleries/:id/upload', to: 'galleries#upload'
  get '/galleries/:id/upload', to: 'galleries#upload'
  resources :galleries
  resources :emails
  resources :bibles
  get "bibles/:id/load/", to:"bibles#load", as:"load_bible"
  get "bibles/:id/load/:book_index", to:"bibles#load_book", as:"load_bible_book"
  get "emails/:id/send/", to:"emails#send_email"
  patch "emails/:id/send/", to:"emails#submit_email_send"
  resources :articles, param: :slug
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
    passwords: 'users/passwords',

  }
  devise_scope :user do
    get "/users/import", to:"users/registrations#import"
    post "/users/import", to:"users/registrations#do_import", as:'user_import'
    get "/users/:id", to:"users/registrations#show", as:'user'
    get "/users/", to:"users/registrations#index"
    get "/users/:id/edit", to:"users/registrations#edit"
    patch "/users/:id", to:"users/registrations#update"
    get "my-profile", to:"users/registrations#edit"
    get "my-courses", to:"users/registrations#my_courses"
    get "my-pets", to:"users/registrations#my_pets"
    delete "/users/:id", to:"users/registrations#destroy"
  end
  get "sign_in", to:redirect('/users/sign_in')
  #get "sign_out", to:redirect('/users/sign_out')
  post "component/:component_id/", to:"pages#component_preview", as:"component"
  post "pages/:slug/component/:component_id/", to:"pages#component_preview", as:"page_component"
  get "component/:component_id/settings", to:"pages#component_settings"
  get "privacy", to:"static_pages#privacy"
  resources 'pages', param: :slug, controller: 'pages'
  # resources 'lessons', param: :slug, controller: 'lessons'

  root to:"pages#home"

resources :courses, param: :slug do
    get "enroll", to:"courses#enroll_student", as:"enrollment"
    post "enroll", to:"courses#enroll"
    get '/lessons/import', to:"lessons#import"
    post '/lessons/import', to:"lessons#do_import"
    delete '/lessons/:slug/delete_file/:id', to: 'lessons#delete_file'
    resources :lessons, param: :slug do
      post '/slides/reorder', to:'lessons#reorder_slides',as:"slides_reorder"
      get '/videos/:filename', to: 'lessons#show_video'
      get '/files/:filename', to: 'lessons#show_file',as:"file"
      get '/slides/new', to:'lessons#new_slide'
      post '/slides/new', to:'lessons#create_slide'
      get '/slides/:index', to:'lessons#show_slide', as:"slide"
      get '/slides/:index/edit', to:'lessons#edit_slide'
      post '/slides/:index/edit', to:'lessons#update_slide'
      delete '/slides/:index', to:'lessons#delete_slide'
      post "/quizzes/:id", to:"quizzes#update"
      post '/upload', to: 'lessons#upload'
      patch '/upload', to: 'lessons#upload'
      post '/chat', to: 'lessons#send_message', as:"chat"
      resource :quiz do
        post '/response', to:'quizzes#student_response'
        post '/slide_response', to:'quizzes#student_response_partial', as:"partial_response"
        get '/:user_id/review', to:'quizzes#instructor_review'
        post '/:user_id/review', to:'quizzes#submit_instructor_review'
      end
    end
    resources :chapters, param: :slug do
      get '/lessons/import', to:"lessons#import_into_chapter"
      post '/lessons/import', to:"lessons#do_import_into_chapter"
      delete '/lessons/:slug/delete_file/:id', to: 'lessons#delete_file'
      get '/lessons/:slug/videos/:filename', to: 'lessons#show_video'
      resources :lessons, param: :slug do
        get '/files/:filename', to: 'lessons#show_file',as:"file"
        get '/videos/:filename', to: 'lessons#show_video'
        patch '/upload', to: 'lessons#upload', as:"upload"
        post '/upload', to: 'lessons#upload'
        get '/slides/new', to:'lessons#new_slide'
        post '/slides/new', to:'lessons#create_slide'
        post '/slides/reorder', to:'lessons#reorder_slides',as:"slides_reorder"
        get '/slides/:index', to:'lessons#show_slide', as:"slide"
        get '/slides/:index/edit', to:'lessons#edit_slide'
        post '/slides/:index/edit', to:'lessons#update_slide'
        delete '/slides/:index', to:'lessons#delete_slide'
        post "/quizzes/:id", to:"quizzes#update"
        resources :quizzes do
          post '/:id/response', to:'quizzes#student_response'
          post '/:id/slide_response', to:'quizzes#student_response_partial'
          get '/:user_id/review', to:'quizzes#instructor_review'
          post '/:user_id/review', to:'quizzes#submit_instructor_review'
        end
      end
    end
  end
end

module CustomUrlHelper
  def lesson_path(lesson)
    if(lesson.chapter.present?)
      course_chapter_lesson_path(lesson.course, lesson.chapter,lesson)
    else
      course_lesson_path(lesson.course,lesson)
    end
  end
  def lesson_url(lesson)
    if(lesson.chapter.present?)
      course_chapter_lesson_url(lesson.course, lesson.chapter,lesson)
    else
      course_lesson_url(lesson.course,lesson)
    end
  end
  def lesson_slide_url(lesson,index)
    if(lesson.chapter.present?)
      course_chapter_lesson_slide_url(lesson.course, lesson.chapter,lesson,index)
    else
      course_lesson_slide_url(lesson.course,lesson,index)
    end
  end
  def lesson_slide_path(lesson,index)
    if(lesson.chapter.present?)
      course_chapter_lesson_slide_url(lesson.course, lesson.chapter,lesson,index)
    else
      course_lesson_slide_url(lesson.course,lesson,index)
    end
  end
  def lesson_slides_reorder_path(lesson)
    if(lesson.chapter.present?)
      course_chapter_lesson_slides_reorder_path(lesson.course,lesson.chapter,lesson)
    else
      course_lesson_slides_reorder_path(lesson.course,lesson)
    end
  end
  def edit_lesson_path(lesson)
    if(lesson.chapter.present?)
      edit_course_chapter_lesson_path(lesson.course, lesson.chapter,lesson)
    else
      edit_course_lesson_path(lesson.course,lesson)
    end
  end
  def new_lesson_path(entity)
    if(entity.class.name == "Chapter")
      new_course_chapter_lesson_path(entity.course, entity)
    elsif(entity.class.name == "Course")
      new_course_lesson_path(entity)
    end
  end
  def new_lesson_url(entity)
    if(entity.class.name == "Chapter")
      new_course_chapter_lesson_url(entity.course, entity)
    elsif(entity.class.name == "Course")
      new_course_lesson_url(entity)
    end
  end
  def edit_lesson_url(lesson)
    if(lesson.chapter.present?)
      edit_course_chapter_lesson_url(lesson.course, lesson.chapter,lesson)
    else
      edit_course_lesson_url(lesson.course,lesson)
    end
  end
  def lesson_upload_path(lesson)
    if(lesson.chapter.present?)
      course_chapter_lesson_path(lesson.course,lesson.chapter,lesson)+"/upload"
    else
      course_lesson_path(lesson.course,lesson)+"/upload"
    end
  end
  def lesson_upload_url(lesson)
    if(lesson.chapter.present?)
      course_chapter_lesson_url(lesson.course,lesson.chapter,lesson)+"/upload"
    else
      course_lesson_url(lesson.course,lesson)+"/upload"
    end
  end
  def lesson_file_path(lesson,filename)
    if(lesson.chapter.present?)
      course_chapter_lesson_file_path(lesson.course,lesson.chapter,lesson,filename)
    else
      course_lesson_file_path(lesson.course,lesson,filename)
    end
  end
  def lesson_file_url(lesson,filename)
    if(lesson.chapter.present?)
      course_chapter_lesson_file_url(lesson.course,lesson.chapter,lesson,filename)
    else
      course_lesson_file_url(lesson.course,lesson,filename)
    end
  end
  def lesson_quiz_path(lesson)
    if(lesson.chapter.present?)
      course_chapter_lesson_quiz_path(lesson.course,lesson.chapter,lesson,lesson.quiz)
    else
      course_lesson_quiz_path(lesson.course,lesson,lesson.quiz)
    end
  end
  def edit_lesson_quiz_path(lesson)
    if(lesson.chapter.present?)
      edit_course_chapter_lesson_quiz_path(lesson.course,lesson.chapter,lesson,lesson.quiz)
    else
      edit_course_lesson_quiz_path(lesson.course,lesson,lesson.quiz)
    end
  end
end

# Works at Rails 4.2.6, for older versions try http://stackoverflow.com/a/31957323/474597
Rails.application.routes.named_routes.url_helpers_module.send(:include, CustomUrlHelper)

app/models/help.rb
# require 'commonmarker'
class Help < ApplicationRecord
  serialize :missing_sections, Array
  after_initialize do |help|
    if(!!help.title && help.slug != help.title.parameterize)
      help.slug = help.title.parameterize
    end
    if(help.missing_sections.present? && help.missing_sections.length > 0)
      help.missing_sections.each do |name|
        if(help.headers.include?(name))
          help.missing_sections.delete(name)
          help.save
        end
      end
    end
  end
  def to_param
    slug
  end
  def categories
    result = [self.title]
    if(self.category.present?)
      result = (Help.find_by slug:category).categories.concat(result)
    end
    return result
  end
  def doc
    if(self.content.nil?)
      return ""
    end
    Kramdown::Document.new(self.content, input:"GFM")
  end
  def doc_description
    if(!!self.description)
      Kramdown::Document.new(self.description, input:"GFM")
    else
      return nil
    end
  end
  def html_content
    if(self.content.nil?)
      return " "
    end
    doc.to_html
  end
  def html_description(class_name=nil)
    if(!!doc_description)
      result = doc_description.to_html
      if(!!class_name)
        wrapper_el = /\<p\>/
        result.gsub!(wrapper_el,"<p class='#{class_name}'>")
      end
      return result
    else
      return ""
    end
  end
  def nodes
    doc.root.children
  end
  def header_objects
    nodes.select{|n| n.type == :header}
  end
  def headers
    header_objects.to_a.map{|h| h.options[:raw_text] }
  end
  def section(name, type=:html)
    return nil if(!name)
    name = name.titleize
    docNodes = self.nodes
    header_objects = docNodes.select{|n| n.type == :header}
    if(headers.include? name)
      # byebug
      sectionHeader = header_objects.select{|n| (n.options[:raw_text] == name)}.first
      index = docNodes.index(sectionHeader)
      if(sectionHeader == header_objects.last)
        output =  docNodes[index,docNodes.length]
      else
        nextIndex = docNodes.index(header_objects[header_objects.index(sectionHeader)+1])
        output = docNodes[index,nextIndex]
      end
      fragment = Kramdown::Document.new("", input:"GFM")
      # byebug
      if(type == :html)
        fragment.root.children = output
        return fragment.to_html
      elsif(type == :text)
      end
    else
      if(!missing_sections.include?(name))
        missing_sections << name
        self.save
      end
      return nil
    end

  end
end

app/controllers/helps_controller.rb
class HelpsController < ApplicationController
  before_action :set_help, except:[:index,:new]
  before_action :authenticate_user!, except:[:index, :show]
  before_action :authorize_action

  # GET /helps
  # GET /helps.json
  def index
    @help = Help.find_by slug:"home"
    @contents = Help.where(category:"home")
    if(@help.restricted)
      auth = (current_user && current_user.isStaff?)
      return unless requester_is_authorized(auth)
    end
    render "show"
  end

  # GET /helps/1
  # GET /helps/1.json
  def show
    # if(@help.restricted)
    #   auth = (current_user && current_user.isStaff?)
    #   return unless requester_is_authorized(auth)
    # end
  end

  # GET /helps/new
  def new
    @help = Help.new
    if(params[:category].present?)
      @category = params[:category]
    end
  end

  # GET /helps/1/edit
  def edit

  end

  # POST /helps
  # POST /helps.json
  def create
    @help = Help.new(help_params)

    respond_to do |format|
      if @help.save
        format.html { redirect_to @help, notice: 'Help article was successfully created.' }
        format.json { render :show, status: :created, location: @help }
      else
        format.html { render :new }
        format.json { render json: @help.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /helps/1
  # PATCH/PUT /helps/1.json
  def update
    respond_to do |format|
      if @help.update(help_params)
        format.html { redirect_to @help, notice: 'Help article was successfully updated.' }
        format.json { render :show, status: :ok, location: @help }
      else
        format.html { render :edit }
        format.json { render json: @help.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /helps/1
  # DELETE /helps/1.json
  def destroy
    @help.destroy
    respond_to do |format|
      format.html { redirect_to helps_url, notice: 'Help article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_help
      params[:slug] = params[:slug].parameterize
      set_resource(param: :slug)
      @contents = Help.where(category:params[:slug].parameterize)
    end

    # Only allow a list of trusted parameters through.
    def help_params
      filter_params(params:[:title, :content, :system, :category, :description])
    end
end

app/helpers/helps_helper.rb
module HelpsHelper
end

app/views/helps/_form.html.erb
<%= bootstrap_form_with(model: help, local: true) do |form| %>
  <% if help.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(help.errors.count, "error") %> prohibited this help from being saved:</h2>

      <ul>
        <% help.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% if(@help.missing_sections.present? && @help.missing_sections.length >0) %>
    <div class="border">
      This help article is missing the following sections referenced in the app:<br>
      <ul>
        <% @help.missing_sections.each do |section| %>
          <li><%= section %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="field col">
      <%= form.text_field :title %>
    </div>
    <div class="field col">
      <% if(@category.present?) %>
        <%= form.text_field :category, value:@category %>
      <% else %>
        <%= form.text_field :category, value:help.category %>
      <% end %>
    </div>
  </div>
  <div class="field">
    <%= form.text_area :description %>
  </div>
  <div class="row">
    <% if(current_user.present? && is_dev(current_user))%>
      <div class="field col-4">
        <%= form.check_box :system %>
      </div>
    <% end %>
  </div>
  <%= render FoldingComponent.new(name:"images", title:"Image Gallery",starts_expanded:false) do |component| %>
  <% component.with(:body) do
      @gallery = Gallery.find_by(name:"Images")
  %>
  <%= link_to('Upload File', "#", class: 'btn btn-sm btn-default', id:"startUpload") %>
  <div class='container' id='fileList'>
    <table class='table'>
      <thead>
        <th>Preview</th>
        <th>Name</th>
        <th>Address in Article</th>
      </thead>
      <tbody>
    <% @gallery.files.each do |f| %>
          <% @gallery.files.each do |file| %>
          <tr>
            <td><%= render("galleries/file_preview", file:file, link:gallery_show_file_path(@gallery, file)+"?filename=#{file.filename.to_s}")%></td>
            <td><%= link_to(file.filename, gallery_show_file_path(@gallery)+"?filename=#{file.filename.to_s}") %></td>
            <td><%= @gallery.url_for(file) %></td>


          </tr>
          <% end %>
        </tbody>
        <% end %>
      </table>
    </div>
    <% end
  end %>
  <%=  %> <%= help_text("model:help:images#uploading", type: :tooltip) %>
  <div class="field">
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<div class="modal fade" id="uploadModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLiveLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Upload Files</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'galleries/add_file', gallery: @gallery %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-default" id="submit">Upload</button>
      </div>
    </div>
  </div>
</div>
<script>
    $('body').ready(()=>{
      completeUpload = ()=>{
        pth = $("#pathHolder").data("path")
        pth = pth.replace('upload','show_files')
        $.get(pth,(content)=>{
            $("#fileList").replaceWith(content)
        })
        $('#uploadModal').modal('hide')
      }
      $('#uploadModal').modal({
        show: false
      })
      $('input','.actions').hide()
      $('#startUpload').click((e)=>{
        e.preventDefault()
        $('#uploadModal').modal('show')
      })
      $('#submit').click(()=>{
        uf = $('form')
        data = new FormData($('form')[0])
        for(let n=0; n < $(':file')[0].files.length; n++)
        {
          data.append("files",$(':file')[0].files[0])
        }
        $.ajax({
            url: $('form')[0].action,
            data: data,
            type: 'POST',
            contentType: false,
            processData: false,
            success:()=>{
              completeUpload()
            }
        });
        path =  $('form')[0].action
        $('.modal-body').empty()
        $('.modal-body').html(`<div class="d-flex justify-content-center"><div class="spinner-grow" role="status">
          <div id="pathHolder" data-path="${path}" style="hidden:true"></div><span class="sr-only">Loading...</span></div></div>`)
      })
    })
  </script>
<style media="screen">
  #help_description{
    min-height: 100px;
    font-family: monospace;
  }
  #help_content{
    min-height: 300px;
    font-family: monospace;
  }
</style>

app/views/helps/_help_nav.html.erb
<nav aria-label="breadcrumb w-100" style="margin-top: 2px;">
  <ol class="breadcrumb">
    <% @help.categories.each do |category| %>
      <% if(category == @help.category) %>
        <li class="breadcrumb-item active"><a href="/help/<%= category %>"><%= category %></a></li>
      <% else %>
        <li class="breadcrumb-item"><a href="/help/<%= category %>"><%= category %></a></li>
      <% end %>
    <% end %>
  </ol>
</nav>

app/views/helps/_helps_table.html.erb
<% if(helps.length > 0) %>
  <div class="border" style="max-width: 30%;">
    <div class="container">
      <strong>Topics</strong>
    </div>
    <ol>
      <% helps.each do |help|  %>
          <li><span><%= link_to(help.title.titleize,help) %></span><% if(current_user.present? && current_user.isAdmin?) %><span style="float:right; margin-right:8px;"><%= edit_button(edit_help_path(help), class:"") %>|<%= delete_button(help,class:"") %></span><% end %></li>
      <% end %>
    </ol>
  </div>
<% end %>

app/views/helps/_nav_items.html.erb
<a class="dropdown-item" href="/help/">Wiki</a>

app/views/helps/edit.html.erb
<%= toolbar([ back_button(:back),view_button(@help)]) %>
<h1>Editing Help</h1>
<%= render 'form', help: @help %>

app/views/helps/index.html.erb
<p id="notice"><%= notice %></p>
<%= toolbar [link_to('Create Documentation', new_help_path, class:"btn btn-sm btn-default")] %>
<h1>Help - <%= Help.first.title %></h1>


<pre><%= Help.first.content %></pre>
<br>

app/views/helps/new.html.erb
<h1>New Help</h1>

<%= render 'form', help: @help %>

<%= link_to 'Back', helps_path %>

app/views/helps/show.html.erb
<style>
  .descriptionCard
  {
    width: 42%;
    padding-left:4px;
    padding-top:4px;
    margin-bottom:5px;
  }
</style>
<%= render "help_nav" %>
<% if(current_user.present? && current_user.isAdmin?) %>
<%= toolbar([back_button(helps_path), edit_button(edit_help_path(@help)), link_to('Create Documentation', new_help_path, class:"btn btn-sm btn-default"),link_to('Create Documentation from here', help_create_subpage_path(@help), class:"btn btn-sm btn-default")],style:"width: 100%; margin-left: 0%;margin-top: -13px;") %>
<% end %>
<h1>Help - <%= @help.title %></h1>
<% if(!!@help.description) %>
  <div class="card descriptionCard border border-dark">
    <%== @help.html_description %>
  </div>
<% end %>
  <div class="container">
    <%= render "helps_table", helps:@contents %>
  </div>
  <%== @help.html_content %>