config/routes.rb
Rails.application.routes.draw do
  get 'live', to:"facebook_videos#live"
  get '/videos/:id/video', to: 'galleries#serve_video'
  get '/images/:id/video', to: 'galleries#serve_video'
  resources :facebook_videos, param: :slug, :path => "videos"
  resources :helps, :path => "help", param: :slug do
  end
  get "help/:category/create", to:"helps#new", as:"help_create_subpage"

  resources :payments do
    post "payment", to:"payments#braintree_processing", as:"braintree_processing"
    get "paid", to:"payments#paid", as:"paid"
  end
  resources :invoices do
    get "checkout", to:"invoices#checkout", as:"checkout"
    post "payment", to:"invoices#payment", as:"payment"
    get "refund", to:"invoices#refund", as:"refund"
  end
  get '/galleries/:id/view', to: 'galleries#show_file',as:"gallery_show_file"
  get '/galleries/:id/select', to: 'galleries#file_select',as:"gallery_file_select"
  get '/galleries/:id/:filename', to: 'galleries#serve_file', as:"file_friendly"
  patch '/galleries/:id/upload', to: 'galleries#upload'
  get '/galleries/:id/upload', to: 'galleries#upload'
  resources :galleries
  resources :emails
  resources :bibles
  get "bibles/:id/load/", to:"bibles#load", as:"load_bible"
  get "bibles/:id/load/:book_index", to:"bibles#load_book", as:"load_bible_book"
  get "emails/:id/send/", to:"emails#send_email"
  patch "emails/:id/send/", to:"emails#submit_email_send"
  resources :articles, param: :slug
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
    passwords: 'users/passwords',

  }
  devise_scope :user do
    get "/users/import", to:"users/registrations#import"
    post "/users/import", to:"users/registrations#do_import", as:'user_import'
    get "/users/:id", to:"users/registrations#show", as:'user'
    get "/users/", to:"users/registrations#index"
    get "/users/:id/edit", to:"users/registrations#edit"
    patch "/users/:id", to:"users/registrations#update"
    get "my-profile", to:"users/registrations#edit"
    get "my-courses", to:"users/registrations#my_courses"
    get "my-pets", to:"users/registrations#my_pets"
    delete "/users/:id", to:"users/registrations#destroy"
  end
  get "sign_in", to:redirect('/users/sign_in')
  #get "sign_out", to:redirect('/users/sign_out')
  post "component/:component_id/", to:"pages#component_preview", as:"component"
  post "pages/:slug/component/:component_id/", to:"pages#component_preview", as:"page_component"
  get "component/:component_id/settings", to:"pages#component_settings"
  get "privacy", to:"static_pages#privacy"
  resources 'pages', param: :slug, controller: 'pages'
  # resources 'lessons', param: :slug, controller: 'lessons'

  root to:"pages#home"

resources :courses, param: :slug do
    get "enroll", to:"courses#enroll_student", as:"enrollment"
    post "enroll", to:"courses#enroll"
    get '/lessons/import', to:"lessons#import"
    post '/lessons/import', to:"lessons#do_import"
    delete '/lessons/:slug/delete_file/:id', to: 'lessons#delete_file'
    resources :lessons, param: :slug do
      post '/slides/reorder', to:'lessons#reorder_slides',as:"slides_reorder"
      get '/videos/:filename', to: 'lessons#show_video'
      get '/files/:filename', to: 'lessons#show_file',as:"file"
      get '/slides/new', to:'lessons#new_slide'
      post '/slides/new', to:'lessons#create_slide'
      get '/slides/:index', to:'lessons#show_slide', as:"slide"
      get '/slides/:index/edit', to:'lessons#edit_slide'
      post '/slides/:index/edit', to:'lessons#update_slide'
      delete '/slides/:index', to:'lessons#delete_slide'
      post "/quizzes/:id", to:"quizzes#update"
      post '/upload', to: 'lessons#upload'
      patch '/upload', to: 'lessons#upload'
      post '/chat', to: 'lessons#send_message', as:"chat"
      resource :quiz do
        post '/response', to:'quizzes#student_response'
        post '/slide_response', to:'quizzes#student_response_partial', as:"partial_response"
        get '/:user_id/review', to:'quizzes#instructor_review'
        post '/:user_id/review', to:'quizzes#submit_instructor_review'
      end
    end
    resources :chapters, param: :slug do
      get '/lessons/import', to:"lessons#import_into_chapter"
      post '/lessons/import', to:"lessons#do_import_into_chapter"
      delete '/lessons/:slug/delete_file/:id', to: 'lessons#delete_file'
      get '/lessons/:slug/videos/:filename', to: 'lessons#show_video'
      resources :lessons, param: :slug do
        get '/files/:filename', to: 'lessons#show_file',as:"file"
        get '/videos/:filename', to: 'lessons#show_video'
        patch '/upload', to: 'lessons#upload', as:"upload"
        post '/upload', to: 'lessons#upload'
        get '/slides/new', to:'lessons#new_slide'
        post '/slides/new', to:'lessons#create_slide'
        post '/slides/reorder', to:'lessons#reorder_slides',as:"slides_reorder"
        get '/slides/:index', to:'lessons#show_slide', as:"slide"
        get '/slides/:index/edit', to:'lessons#edit_slide'
        post '/slides/:index/edit', to:'lessons#update_slide'
        delete '/slides/:index', to:'lessons#delete_slide'
        post "/quizzes/:id", to:"quizzes#update"
        resources :quizzes do
          post '/:id/response', to:'quizzes#student_response'
          post '/:id/slide_response', to:'quizzes#student_response_partial'
          get '/:user_id/review', to:'quizzes#instructor_review'
          post '/:user_id/review', to:'quizzes#submit_instructor_review'
        end
      end
    end
  end
end

module CustomUrlHelper
  def lesson_path(lesson)
    if(lesson.chapter.present?)
      course_chapter_lesson_path(lesson.course, lesson.chapter,lesson)
    else
      course_lesson_path(lesson.course,lesson)
    end
  end
  def lesson_url(lesson)
    if(lesson.chapter.present?)
      course_chapter_lesson_url(lesson.course, lesson.chapter,lesson)
    else
      course_lesson_url(lesson.course,lesson)
    end
  end
  def lesson_slide_url(lesson,index)
    if(lesson.chapter.present?)
      course_chapter_lesson_slide_url(lesson.course, lesson.chapter,lesson,index)
    else
      course_lesson_slide_url(lesson.course,lesson,index)
    end
  end
  def lesson_slide_path(lesson,index)
    if(lesson.chapter.present?)
      course_chapter_lesson_slide_url(lesson.course, lesson.chapter,lesson,index)
    else
      course_lesson_slide_url(lesson.course,lesson,index)
    end
  end
  def lesson_slides_reorder_path(lesson)
    if(lesson.chapter.present?)
      course_chapter_lesson_slides_reorder_path(lesson.course,lesson.chapter,lesson)
    else
      course_lesson_slides_reorder_path(lesson.course,lesson)
    end
  end
  def edit_lesson_path(lesson)
    if(lesson.chapter.present?)
      edit_course_chapter_lesson_path(lesson.course, lesson.chapter,lesson)
    else
      edit_course_lesson_path(lesson.course,lesson)
    end
  end
  def new_lesson_path(entity)
    if(entity.class.name == "Chapter")
      new_course_chapter_lesson_path(entity.course, entity)
    elsif(entity.class.name == "Course")
      new_course_lesson_path(entity)
    end
  end
  def new_lesson_url(entity)
    if(entity.class.name == "Chapter")
      new_course_chapter_lesson_url(entity.course, entity)
    elsif(entity.class.name == "Course")
      new_course_lesson_url(entity)
    end
  end
  def edit_lesson_url(lesson)
    if(lesson.chapter.present?)
      edit_course_chapter_lesson_url(lesson.course, lesson.chapter,lesson)
    else
      edit_course_lesson_url(lesson.course,lesson)
    end
  end
  def lesson_upload_path(lesson)
    if(lesson.chapter.present?)
      course_chapter_lesson_path(lesson.course,lesson.chapter,lesson)+"/upload"
    else
      course_lesson_path(lesson.course,lesson)+"/upload"
    end
  end
  def lesson_upload_url(lesson)
    if(lesson.chapter.present?)
      course_chapter_lesson_url(lesson.course,lesson.chapter,lesson)+"/upload"
    else
      course_lesson_url(lesson.course,lesson)+"/upload"
    end
  end
  def lesson_file_path(lesson,filename)
    if(lesson.chapter.present?)
      course_chapter_lesson_file_path(lesson.course,lesson.chapter,lesson,filename)
    else
      course_lesson_file_path(lesson.course,lesson,filename)
    end
  end
  def lesson_file_url(lesson,filename)
    if(lesson.chapter.present?)
      course_chapter_lesson_file_url(lesson.course,lesson.chapter,lesson,filename)
    else
      course_lesson_file_url(lesson.course,lesson,filename)
    end
  end
  def lesson_quiz_path(lesson)
    if(lesson.chapter.present?)
      course_chapter_lesson_quiz_path(lesson.course,lesson.chapter,lesson,lesson.quiz)
    else
      course_lesson_quiz_path(lesson.course,lesson,lesson.quiz)
    end
  end
  def edit_lesson_quiz_path(lesson)
    if(lesson.chapter.present?)
      edit_course_chapter_lesson_quiz_path(lesson.course,lesson.chapter,lesson,lesson.quiz)
    else
      edit_course_lesson_quiz_path(lesson.course,lesson,lesson.quiz)
    end
  end
end

# Works at Rails 4.2.6, for older versions try http://stackoverflow.com/a/31957323/474597
Rails.application.routes.named_routes.url_helpers_module.send(:include, CustomUrlHelper)

app/models/payment.rb
class Payment < ApplicationRecord
  monetize :amount_cents
  monetize :amount_in_btc_cents, with_currency: :btc
  belongs_to :user
  belongs_to :invoice, optional:true
  belongs_to :bitcoin_wallet, optional:true
  def payment_type
    if(invoice.present?)
      return "Payment"
    else
      return "Donation"
    end
  end

  def status
    if(self.payment_method == "credit_card" && self.transaction_id.present?)
      data = Payment.gateway.transaction.find(self.transaction_id)
      return data.status.to_sym
    elsif(self.payment_method == "credit_card" && self.transaction_id.nil?)
      return :pending
    elsif(self.payment_method == "bitcoin")
      if(self.payment_address.present? && self.transaction_id.nil?)
        address_data = Payment.block_explorer.address_info(address:self.payment_address)
        if(address_data["txrefs"].present? && address_data["txrefs"].length > 0)
          self.transaction_id = address_data["txrefs"].last["tx_hash"]
          self.save
        end
      end
      if(self.transaction_id.present?)
        tx_data = Payment.block_explorer.transaction(transaction_id:self.transaction_id)
        if(tx_data["confirmations"] > 0 && tx_data["confirmations"] < 6)
          return :settling
        elsif(tx_data["confirmations"] >= 6)
          return :settled
        end
      else
        return :pending
      end
    end
  end
  def self.categories
    return [["General Church Budget","general_church_budget"]]
  end
  def self.payment_methods
    return [["Credit/Debit Card","credit_card"],["Bitcoin","bitcoin"]]
  end
  def self.gateway
    return Braintree::Gateway.new(environment: :sandbox,merchant_id:ENV["BT_MERCHANT_ID"], public_key:ENV["BT_PUBLIC_KEY"], private_key:ENV["BT_PRIVATE_KEY"])
  end
  def self.status_info(status)
    case status.to_sym
    when :submitted_for_settlement
      "The transaction has been submitted for settlement and will be included in the next settlement batch. Settlement happens nightly – the exact time depends on the processor."
    when :settling
      "The transaction is in the process of being settled. This is a transitory state. A transaction can't be voided once it reaches Settling status, but can be refunded."
    when :settled
      "The transaction has been settled."
    when :voided
      "The transaction was voided prior to settlement."
    when :unpaid
      "The user has added the course but has not yet paid."
    end
  end
  def self.block_explorer
    return BlockcypherApi.new
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy, :braintree_processing,:paid]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
    authorized = (current_user && (current_user == @payment.user))
    return unless requester_is_authorized(authorized)

    if(@payment.payment_method == "bitcoin")
      bitcoin_payment_params
      request_data = get_payment_request(address:@bitcoin_address,amount:@payment.amount_in_btc.to_s,message:ERB::Util.url_encode(@payment.category.titleize))
      @payment_request = request_data[:request]
      @qr_code = request_data[:qr_code]
      @address_qr_code = request_data[:address_qr_code]
    else
      @client_token = Payment.gateway.client_token.generate
    end
  end

  def braintree_processing
    authorized = (current_user && (current_user == @payment.user))
    return unless requester_is_authorized(authorized)
    params = braintree_params
    result = Payment.gateway.transaction.sale(
      :amount => @payment.amount.to_s,
      :payment_method_nonce => params[:nonce],
      :options => {
        :submit_for_settlement => true
      }
    )
    if result.success?
      @payment.transaction_id = result.transaction.id


      @payment.save
      render :json => result
      return
    else
      puts(result.message)
      render :json => result
    end
  end
  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)
    @payment.user = current_user
    respond_to do |format|
      if @payment.save
        format.html { redirect_to payment_payment_path(@payment) }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      if(params[:id])
        @payment = Payment.find(params[:id])
      elsif(params[:payment_id])
        @payment = Payment.find(params[:payment_id])
      end
      if(@payment.invoice)
        @invoice = @payment.invoice
      end
    end

    def bitcoin_payment_params
      if(@payment.payment_address.present?)
        @bitcoin_address = @payment.payment_address
      else
        @payment.payment_address = BitcoinWallet.first.use_next_multisig_address
        @bitcoin_address = @payment.payment_address
      end
      if(@payment.amount_in_btc.nil?)
        @payment.amount_in_btc = Money.new(0, 'BTC')
        @payment.amount_in_btc = @payment.amount_in_btc + @payment.amount
      end
      @payment.save()
    end

    def get_payment_request(**args)
      BitcoinWallet.get_payment_request(**args)
    end
    # Only allow a list of trusted parameters through.
    def payment_params
      params.require(:payment).permit(:category, :amount, :payment_method)
    end
    def braintree_params
      params.permit(:nonce)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_bitcoin_payment.html.erb
Amount Requested: ₿ <b><%= @payment.amount_in_btc %></b> ($<%= @payment.amount %> <%= @payment.amount_currency %>)<br>
Payment Address: <%= @payment.payment_address %><br>
<nav>
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <a class="nav-item nav-link active" id="nav-pr-tab" data-toggle="tab" href="#nav-pr" role="tab" aria-controls="nav-pr" aria-selected="true">Payment Request</a>
    <a class="nav-item nav-link" id="nav-addr-tab" data-toggle="tab" href="#nav-addr" role="tab" aria-controls="nav-addr" aria-selected="false">Legacy QR Code</a>
  </div>
</nav>
<div class="tab-content" id="nav-tabContent">
  <div class="tab-pane fade show active" id="nav-pr" role="tabpanel" aria-labelledby="nav-pr-tab"><div class="container" style="margin-left: 32%;
      margin-top: 3%;
      margin-bottom: 3%;">
    <%== @qr_code.as_svg(
    offset: 0,
    color: '000',
    shape_rendering: 'crispEdges',
    module_size: 6,
    standalone: true
    ) %>
  </div>
</div>
  <div class="tab-pane fade" id="nav-addr" role="tabpanel" aria-labelledby="nav-addr-tab"><div class="tab-pane fade show active" id="nav-pr" role="tabpanel" aria-labelledby="nav-pr-tab"><div class="container" style="margin-left: 40%;
      margin-top: 3%;
      margin-bottom: 3%;">
    <%== @address_qr_code.as_svg(
    offset: 0,
    color: '000',
    shape_rendering: 'crispEdges',
    module_size: 6,
    standalone: true
    ) %>
  </div>
</div>
</div>

app/views/payments/_braintree_payment.html.erb
<script src="https://js.braintreegateway.com/web/dropin/1.22.1/js/dropin.js"></script>
<script src="https://js.braintreegateway.com/web/3.62.0/js/data-collector.min.js"></script>
<div id="dropin-container"></div>
<% if(@payment.payment_type == "Payment") %>
<button id="submit-button" class="button button--small button--green">Checkout</button>
<% else %>
<button id="submit-button" class="button button--small button--green">Give Now</button>
<% end %>
<style media="screen">
  .button {
  cursor: pointer;
  font-weight: 500;
  left: 3px;
  line-height: inherit;
  position: relative;
  text-decoration: none;
  text-align: center;
  border-style: solid;
  border-width: 1px;
  border-radius: 3px;
  -webkit-appearance: none;
  -moz-appearance: none;
  display: inline-block;
}

.button--small {
  padding: 10px 20px;
  font-size: 0.875rem;
}

.button--green {
  outline: none;
  background-color: #64d18a;
  border-color: #64d18a;
  color: white;
  transition: all 200ms ease;
}

.button--green:hover {
  background-color: #8bdda8;
  color: white;
}
</style>
<script type="text/javascript">
  var button = document.querySelector('#submit-button');

braintree.dropin.create({
  authorization: `<%= @client_token %>`,
  selector: '#dropin-container'
},
function (err, instance) {
  button.addEventListener('click', function () {
    instance.requestPaymentMethod(function (err, payload) {
      $.ajax({
            url: "<%= payment_braintree_processing_url(@payment) %>",
            data: payload,
            type: "POST",
            success:(data)=>{
              console.log(data)
              window.location = "<%= payment_paid_url(@payment) %>"
            }
        });
    });
  })
});
</script>

app/views/payments/_form.html.erb
<%= bootstrap_form_with(model: payment, local: true) do |form| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
      <% if(payment.amount.nil?) %>
        <div class="field">
          <%= form.select :category, Payment.categories %>
        </div>
      <% else %>
          <%= form.hidden_field :category, value:"Payment" %>
      <% end %>
    </div>
    <div class="field">
      <%= form.select :payment_method, Payment.payment_methods, include_blank:"Select a payment method..." %>
    </div>
    <% if(payment.amount.nil?) %>
      <div class="field">
        <%= form.number_field :amount, prepend: "$" %>
      </div>
    <% else %>
      <%= form.hidden_field :amount, value:payment.amount %>
    <% end %>
  <div class="actions">
    <%= form.submit "Checkout" %>
  </div>
<% end %>

app/views/payments/_show.html.erb
<% if( @payment.invoice.present? )%>
<h1>Payment - Invoice #<%= @payment.invoice.number %></h1>
<% else %>
<h1>Payment - <%= @payment.payment_type %></h1>
<% end %>
Amount: <%= @payment.amount %> <br>
Payment Method: <%= @payment.payment_method.titleize %><br>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<%= toolbar(link_to('New Payment', new_payment_path, class:"btn btn-sm btn-default")) %>

<h1>Payments</h1>

<%= render(TableComponent.new(records:@payments,fields:[:user_name, :amount, :category, :payment_method])) do |component| %>
  <% component.with(:placeholder) do %>
      There are no payments yet.
  <% end %>
<% end %>

app/views/payments/new.html.erb
<%= toolbar([back_button(:back)]) %>
<h1>Make a Donation</h1>

<%= render 'form', payment: @payment %>

app/views/payments/paid.html.erb
<% if( @payment.invoice.present? )%>
<div class="container">
  <div class="alert alert-success" role="alert">
    ✓ Invoice Paid - Thank you!
  </div>
  <% if(@payment.invoice.present?) %>
  <%= render("invoices/show", invoice:@payment.invoice) %>

  <% end %>
  Proceed to <a class="btn btn-sm btn-default" href="/my-courses/">Your Courses</a>
</div>
<% else %>
<div class="container">
  <div class="alert alert-success" role="alert">
    ✓ Donation Recieved - Thank you!
  </div>
  <%= render "show" %>
  Proceed to <a class="btn btn-sm btn-default" href="/my-courses/">Your Courses</a>
</div>
<% end %>

app/views/payments/payment.html.erb
<%= render "show" %>

app/views/payments/show.html.erb
<%= toolbar([back_button(:back)]) %>
<%= render "show" %>

<% if(@payment.user != current_user) %>
From: <%= @payment.user.name %><br>
For: <%= link_to "Invoice ##{@payment.invoice.number.to_s}", @payment.invoice %><br>
<% end %>
<% if(@payment.payment_type != "Payment") %>
Type: <%= @payment.payment_type %><br>
<% end %>
<% if(@payment.invoice.present?) %>
<%= render("invoices/show", invoice:@payment.invoice) %>

<% end %>
<% if(@payment.payment_method == "credit_card")%>
<%= render "braintree_payment" %>
<% elsif(@payment.payment_method == "bitcoin") %>
<%= render "bitcoin_payment" %>
<% end %>

app/views/payments/show0.html.erb
<h1>Invoice #<%= @invoice.number %></h1>
<% if(current_user != @invoice.user) %>
<div class="border">
  <div class="row">
    <div class="col">
      <strong>Client Name:</strong>&nbsp<%= @invoice.user.name %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <strong>Status:</strong>&nbsp<%= @invoice.status.titleize %><span title="<%= @invoice.status_info(@invoice.status) %>" style="font-size: large; color: maroon;">&nbsp🛈</span>
    </div>
  </div>
</div>
<% if(@invoice.status == "unpaid" || @invoice.status == "voided" || @invoice.status == "refunded" ) %>
  <%= delete_button(@invoice) %>
<% else %>
  <%= link_to 'Refund', invoice_refund_url(@invoice), title:"Click here to refund, or prevent settlement if the payment has not yet settled.", data: { confirm: 'Are you sure?' },class: 'btn btn-sm btn-danger' %>
<% end %>
<% else %>
  <%= link_to 'Checkout', invoice_checkout_path(@invoice), class: 'btn btn-sm btn-default' %>
<% end %>
<%= link_to 'Back', :back, class: 'btn btn-sm btn-secondary' %>
<%= render "show" %>
<% if(current_user == @invoice.user) %>
  <%= link_to 'Checkout', invoice_checkout_path(@invoice), class: 'btn btn-sm btn-default' %>
<% end %>